baseURL = "https://hugo-uffizzi-test.netlify.com"
disableLanguages = []
disqusShortname = "agico"
paginate = "6"
summaryLength = "10"
theme = "agico-hugo"
title = "Uffizzi"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
footer_content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit."
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
footer_content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit."
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "#"
name = "Privacy Policy"
weight = 1
[[menu.footer]]
URL = "service"
name = "Services"
weight = 2
[[menu.footer]]
URL = "contact"
name = "Contact us"
weight = 3
[[menu.footer]]
URL = "about"
name = "About us"
weight = 4
[[menu.footer]]
URL = "about"
name = "Company History"
weight = 5
[[menu.main]]
URL = "career"
name = "Career"
parent = "Pages"
weight = 1
[[menu.main]]
URL = "pricing"
name = "Pricing"
parent = "Pages"
weight = 2
[[menu.main]]
hasChildren = true
name = "Pages"
weight = 6
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.main]]
URL = "team"
name = "Team"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "service"
name = "Service"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = "626 Main St, Ste 203, Nashville, TN 37206"
author = "Uffizzi"
contact_form_action = "#"
description = "Drop us a line"
email = "info@uffizzi.cloud"
google_analitycs_id = "Your ID"
logo = "images/uffizzi-logo-white-yellow.png"
mobile = "615-426-7141"
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.navigation_button]
enable = true
label = "sign up"
link = "#"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/font-awesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
URL = "https://facebook.com/themefisher"
icon = "fa-facebook"
[[params.social]]
URL = "https://twitter.com/themefisher"
icon = "fa-twitter"
[[params.social]]
URL = "https://github.com/themefisher"
icon = "fa-github"
[[params.social]]
URL = "https://instagram.com/themefisher"
icon = "fa-instagram"
